version: "3.7"
services:
  stocks-forwarder:
    build:
      context: .
      dockerfile: build/package/Dockerfile
    ports:
      - "8080:8080"
    environment:
      - "STOCKS_PERCENTAGE_API=http://percentages-mock-server:8083/percentages"
  percentages-mock-server:
    image: jordimartin/mmock
    expose:
      - "8083"
    ports:
      - "8082:8082"
    volumes:
      - ./tests/percentages-mock-config:/config
